---
- hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: launch the instances nginx,tomcat,mq
      ec2:
        key_name: jenkins
        region: ap-south-1
        vpc_id: vpc-04efc833a8e4caaa9
        vpc_subnet_id: subnet-0d1039a6090769a67
        assign_public_ip: yes
        group_id: sg-0481f6bac5ffeb8f0
        instance_type: t2.micro
        image: ami-0d81306eddc614a45
        monitoring: no
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: Node1
        count_tag:
        Name: Node1
        exact_count: 1
        register: ec2_info

