---
- hosts: test
  become: yes
  gather_facts: false
  vars:
      ec2_access_key: AKIAW4QBUP22KUM3FBE7
      ec2_secret_key: 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
  tasks:
    - name: launch the instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: jenkins
        region: ap-south-1
        vpc_id: vpc-04efc833a8e4caaa9
        vpc_subnet_id: subnet-0d1039a6090769a67
        assign_public_ip: yes
        group_id: sg-0481f6bac5ffeb8f0
        instance_type: t2.micro
        image: ami-0d81306eddc614a45
        state: present
      register: ec2
        

