---
- hosts: localhost
  become: yes
  gather_facts: false
  connection: local
  tasks:
    - name: install ec2 server
      ec2:
        image: ami-0d81306eddc614a45
        region: ap-south-1
        key_name: jenkins
        zone: ap-south-1a
        tags: 
          Name: "ansible-server"
        instance_type: t2.micro
        count: 1
