---
- hosts: test
  gather_facts: false
  become: yes
  tags: provisioning

  vars:
    keypair: jenkins
    instance_type: t2.micro
    image: ami-0d81306eddc614a45
    wait: yes
    count: 1
    region: ap-south-1
    security_group: jenkins-sg
    ec2_access_key: AKIAW4QBUP22KUM3FBE7
    ec2_secret_key: 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
    
  tasks:
    - name: create ec2 instance
      local_action: ec2
                    aws_access_key={{ec2_access_key}}
                    aws_secret_key={{ec2_secret_key}}
                    instance_type={{instance_type}}
                    image={{image}}
                    wait=true
                    region={{region}}
                    keypair={{keypair}}
                    group={{security_group}}
                    count={{count}}
