---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: install git
      yum:
        name: git
        state: present
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
      notify: restart httpd
    - name: create file
      file:
        path: "/var/www/html/index.html"
        state: touch
        mode: 0777
    - name: inserting content into index.html
      copy:
        dest: "/var/www/html/index.html"
        content: |
          jenkins-ansible deployment
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted 
