---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: install git
      action: yum pkg=git state=present
    - name: install httpd
      command: yum pkg=httpd state=present
    - name: start httpd
      action: service name=httpd state=started
      notify: restart httpd
    - name: create file
      file:
        path: "/var/www/html/index.html"
        state: touch
    - name: inserting content into index.html
      copy:
        dest: "/var/www/html/index.html"
        content: |
          jenkins-ansible deployment
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted 
